#!/bin/sh

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# COPYRIGHT 2017 Pluribus Networks Inc. All Rights Reserved.
#

PKG_IMG_ROOT=$1

if [ "x$PKG_IMG_ROOT" = "x" ]
then
	echo "Usage: $0 <pkg_img_root>"
	exit 1
fi

#
# Delete most locales except for a few basic ones.
# The all-locales package gets pulled in via a dependency
# chain which is quite hard to change. All locales are
# not needed for a Live Install ISO.
#
(cd $PKG_IMG_ROOT/usr/lib/locale
 ls | egrep -v 'en_US.*|C|POSIX' | while read loc
 do
	rm -r $loc
 done)
