#!/bin/sh

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# COPYRIGHT 2017 Pluribus Networks Inc. All Rights Reserved.
#

PKG_IMG_ROOT=$1

cat $PKG_IMG_ROOT/lib/svc/method/media-assembly | nawk ' BEGIN { matched=0; }
/^	\/usr\/bin\/kbd -s/ { print "	/usr/bin/kbd -s US-English"; matched = 1; }
/^	\/usr\/sbin\/set_lang/ { print "	#"; matched = 1; }
{ if (matched == 0) {
	print $0;
  }
  matched = 0;
}' > $PKG_IMG_ROOT/lib/svc/method/media-assembly.new
cp $PKG_IMG_ROOT/lib/svc/method/media-assembly.new $PKG_IMG_ROOT/lib/svc/method/media-assembly
rm $PKG_IMG_ROOT/lib/svc/method/media-assembly.new

rm -f $PKG_IMG_ROOT/var/saf/zsmon/log
if [ -f /usr/share/sysinstall/ntp.conf ]
then
	cp /usr/share/sysinstall/ntp.conf $PKG_IMG_ROOT/etc/inet/ntp.conf
else
	cp /usr/share/sysinstall/ntp.conf.default $PKG_IMG_ROOT/etc/inet/ntp.conf
fi

if [ -f /usr/share/sysinstall/eventhook ]
then
	cp /usr/share/sysinstall/eventhook $PKG_IMG_ROOT/etc/dhcp
	chmod 0555 $PKG_IMG_ROOT/etc/dhcp/eventhook
fi
