#!/bin/sh

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# COPYRIGHT 2017 Pluribus Networks Inc. All Rights Reserved.
#

PKG_IMG_ROOT=$1

cat $PKG_IMG_ROOT/lib/svc/method/media-assembly | nawk '
/^	\/usr\/bin\/kbd -s/ { print "   /usr/bin/kbd -s US-English" }
/^	\/usr\/sbin\/set_lang/ { print "        #" }' > $PKG_IMG_ROOT/lib/svc/method/media-assembly.new
cp $PKG_IMG_ROOT/lib/svc/method/media-assembly.new $PKG_IMG_ROOT/lib/svc/method/media-assembly
rm $PKG_IMG_ROOT/lib/svc/method/media-assembly.new
