#!/sbin/sh

#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# COPYRIGHT 2017 Pluribus Networks Inc. All Rights Reserved.
#

. /lib/svc/share/smf_include.sh

#
# This will allow the executed script to determine whether it is
# called from SMF service.
#
export SMF_FMRI

case "$1" in
'start')
	#
	# Disable service if not automated install
	#
	if [ -f /usr/share/auto_sysinstall ]
	then
		((exec /usr/bin/sysinstall)&)
	else
		svcadm disable $SMF_FMRI
	fi
	;;

*)
	echo "Usage: $0 start"
	exit 1
	;;

esac
exit $SMF_EXIT_OK

